-- This migration is intentionally non-blocking.
--
-- The original migration created
-- "operations_user_id_entity_type_entity_id_server_seq_idx" with
-- CREATE INDEX CONCURRENTLY. On production-sized operation logs this can run
-- longer than a normal app deploy and interact badly with Prisma's advisory
-- migration lock.
--
-- Build the physical index as a separate off-hours deploy step instead:
-- RUN_POST_MIGRATION_INDEXES=true ./scripts/deploy.sh
